from __future__ import annotations

import csv
from pathlib import Path
from typing import Iterable

import pandas as pd
import requests


ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = ROOT / "data"
OUT_DIR = DATA_DIR / "7_teaching_workflows"


def _ensure_dir() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)


def _read_single_column_csv(path: Path, column_name: str = "SMILES", limit: int | None = None) -> pd.DataFrame:
    df = pd.read_csv(path)
    if len(df.columns) == 1 and df.columns[0] != column_name:
        df = df.rename(columns={df.columns[0]: column_name})
    if limit is not None:
        df = df.head(limit).copy()
    return df


def _fetch_chembl_activities(
    target_chembl_id: str,
    *,
    target_name: str,
    standard_type: str = "IC50",
    limit: int = 1000,
) -> pd.DataFrame:
    url = (
        "https://www.ebi.ac.uk/chembl/api/data/activity.json"
        f"?target_chembl_id={target_chembl_id}&standard_type={standard_type}&limit={limit}"
    )
    response = requests.get(url, timeout=60)
    response.raise_for_status()
    raw = pd.DataFrame(response.json()["activities"])

    keep = raw[
        [
            "molecule_chembl_id",
            "canonical_smiles",
            "standard_value",
            "standard_units",
            "pchembl_value",
            "assay_chembl_id",
        ]
    ].copy()
    keep = keep.dropna(subset=["molecule_chembl_id", "canonical_smiles", "standard_value"])
    keep["standard_value"] = pd.to_numeric(keep["standard_value"], errors="coerce")
    keep["pchembl_value"] = pd.to_numeric(keep["pchembl_value"], errors="coerce")
    keep = keep.dropna(subset=["standard_value"])
    keep = keep[keep["standard_value"] > 0].copy()
    keep["target_chembl_id"] = target_chembl_id
    keep["target_name"] = target_name
    keep["name"] = keep["molecule_chembl_id"]

    # Prefer the most informative record per molecule:
    # highest pChEMBL when available, otherwise lowest IC50.
    keep = keep.sort_values(
        ["molecule_chembl_id", "pchembl_value", "standard_value"],
        ascending=[True, False, True],
    )
    keep = keep.groupby("molecule_chembl_id", as_index=False).first()
    keep = keep.rename(
        columns={
            "molecule_chembl_id": "ChEMBL_ID",
            "canonical_smiles": "SMILES",
            "standard_value": "IC50_nM",
            "standard_units": "IC50_units",
            "pchembl_value": "pChEMBL",
            "assay_chembl_id": "Assay_ID",
        }
    )
    return keep[
        [
            "ChEMBL_ID",
            "name",
            "SMILES",
            "IC50_nM",
            "IC50_units",
            "pChEMBL",
            "Assay_ID",
            "target_chembl_id",
            "target_name",
        ]
    ].reset_index(drop=True)


def _write_csv(path: Path, frame: pd.DataFrame) -> None:
    frame.to_csv(path, index=False, quoting=csv.QUOTE_MINIMAL)


def _write_readme(files: Iterable[str]) -> None:
    text = f"""# Teaching Workflow Data

This folder contains ready-to-use example datasets for five teaching workflows in the `chem-inf-widgets` Orange add-on.

Generated by:
`data/python_code/build_teaching_workflow_data.py`

Files:
{chr(10).join(f"- `{name}`" for name in files)}

Suggested workflows:

1. `01_standardization_smiles.csv`
Use with: `Mol Standardizer -> Drug Filter -> Scaffold Analysis`
Goal: show how cleanup and normalization change downstream chemistry.

2. `02_diversity_smiles.csv`
Use with: `Fingerprint Generator -> Diversity Picker -> Scaffold Analysis`
Goal: compare diverse subset selection methods on a medium-sized library.

3. `03_activity_cliffs_vegfr2_ic50.csv`
Use with: `Mol Standardizer -> Activity Cliff Finder -> Molecular Viewer`
Goal: identify highly similar compounds with large potency differences.

4. `04_qsar_vegfr2_ic50.csv`
Use with: `Mol Standardizer -> Mol Descriptors 2 or Fingerprint Generator -> QSAR Regression`
Goal: build and diagnose a regression model on real ChEMBL VEGFR2 data.

5. `05_ad_reference_vegfr2_ic50.csv` and `05_ad_query_vegfr2_ic50.csv`
Use with: `Mol Standardizer -> descriptor widget -> Applicability Domain`
Goal: fit AD on a reference set and probe a separate query set.

Notes:
- The VEGFR2 datasets were retrieved from the official ChEMBL API endpoint for target `CHEMBL279` with `standard_type=IC50`.
- Rows are deduplicated by molecule, preferring the highest available `pChEMBL` and otherwise the lowest `IC50`.
- The AD files are deterministic row splits of the same curated VEGFR2 set.
"""
    (OUT_DIR / "README.md").write_text(text)


def main() -> None:
    _ensure_dir()

    standardization = _read_single_column_csv(DATA_DIR / "1_standardisation" / "2500.csv", limit=250)
    diversity = _read_single_column_csv(DATA_DIR / "1_standardisation" / "2500.csv", limit=180)

    vegfr2 = _fetch_chembl_activities("CHEMBL279", target_name="Vascular endothelial growth factor receptor 2")
    vegfr2_qsar = vegfr2.dropna(subset=["pChEMBL"]).copy().reset_index(drop=True)

    ad_reference = vegfr2_qsar.iloc[:120].reset_index(drop=True)
    ad_query = vegfr2_qsar.iloc[120:180].reset_index(drop=True)

    outputs = {
        "01_standardization_smiles.csv": standardization,
        "02_diversity_smiles.csv": diversity,
        "03_activity_cliffs_vegfr2_ic50.csv": vegfr2,
        "04_qsar_vegfr2_ic50.csv": vegfr2_qsar,
        "05_ad_reference_vegfr2_ic50.csv": ad_reference,
        "05_ad_query_vegfr2_ic50.csv": ad_query,
    }

    for filename, frame in outputs.items():
        _write_csv(OUT_DIR / filename, frame)

    _write_readme(outputs.keys())
    print(f"Wrote {len(outputs)} datasets to {OUT_DIR}")


if __name__ == "__main__":
    main()
